version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "elearning-dev"
s3_bucket = "e-learning-lambdas"
s3_prefix = "elearning-dev"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

